version: "3.8"

services:
  # 🧱 Servicio de autenticación (Keycloak)
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_data:/opt/keycloak/data         # Persistencia local
      - ./import:/opt/keycloak/data/import         # Importación automática del realm

  # ⚙️ Servicio del backend (API con Spring Boot y HTTPS)
  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      SPRING_APPLICATION_NAME: demo
      SERVER_PORT: 8443
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY_STORE: /app/keystore.p12
      SERVER_SSL_KEY_STORE_PASSWORD: 123456
      SERVER_SSL_KEY_STORE_TYPE: PKCS12
      SERVER_SSL_KEY_ALIAS: api-cert
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/parcial-realm
    ports:
      - "8443:8443"
    depends_on:
      - keycloak
    volumes:
      - ./API/src/main/resources/keystore.p12:/app/keystore.p12

  # 💻 Servicio del frontend (Vite + Nginx)
  frontend:
    build:
      context: ./Frontend/Logiin
      dockerfile: Dockerfile
    environment:
      # ⚠️ Usa HTTPS y el nombre del contenedor "api"
      - VITE_API_URL=https://api:8443
    ports:
      - "3000:80"
    depends_on:
      - api
