version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8081:8081"
    volumes:
      - ./keycloak_data:/opt/keycloak/data        # Persistencia local
      - ./import:/opt/keycloak/data/import       # Importación automática

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      # Apunta al Keycloak dentro de la red de Docker (nombre del servicio, no localhost)
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/parcial-realm
    ports:
      - "8081:8080"
    depends_on:
      - keycloak

  frontend:
    build:
      context: ./Frontend/Logiin
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - api
    environment:
      - VITE_API_URL=http://api:8080
