version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_data:/opt/keycloak/data
      - ./import:/opt/keycloak/data/import

  api:
    build:
      context: ./node-api
      dockerfile: Dockerfile
    environment:
      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/parcial-realm
      PORT: 8443
    volumes:
      - ./node-api/certs:/app/certs
    ports:
      - "8443:8443"
    depends_on:
      - keycloak

  frontend:
    build:
      context: ./Frontend/Logiin
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=https://api:8443
    volumes:
      - ./certs:/app/certs
    depends_on:
      - api
