version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_data:/opt/keycloak/data
      - ./import:/opt/keycloak/data/import

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8443
      SERVER_SSL_ENABLED: "true"
      SERVER_SSL_KEY_STORE: /app/keystore.p12
      SERVER_SSL_KEY_STORE_PASSWORD: yourpassword
      SERVER_SSL_KEY_STORE_TYPE: PKCS12
      KEYCLOAK_ISSUER_URI: https://keycloak:8443/realms/parcial-realm
    volumes:
      - ./API/keystore.p12:/app/keystore.p12
    ports:
      - "8443:8443"
    depends_on:
      - keycloak

  frontend:
    build:
      context: ./Frontend/Logiin
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=https://localhost:8443
    depends_on:
      - api
